memperbaiki edit
inventorydita/fe_inventory pull request #17
Opened 2021-08-14 16:55 UTC by kevinriah

2021-08-20 10:00 UTC, kevinriah commented
ss

2021-08-21 14:26 UTC, triandamai requested changes
cek dlu

2021-08-21 14:26 UTC, triandamai commented on src/views/barang/detailbarang.vue
> +              this.getDataDetailBarang();
tambah buat refresh datanya `this.getDataDetailBarang();`

2021-08-21 14:26 UTC, triandamai commented on src/views/barang/editdetailbarang.vue
> +      // object destruction (21)
`then(({status,data})-=>{
    
})`

2021-08-21 14:26 UTC, triandamai commented on src/views/pemasok/editPemasok.vue
> +      // object destruction (21)
`then(({status,data})=>{})`

2021-08-21 16:34 UTC, triandamai approved these changes

2021-08-21 16:34 UTC, merged