menambah form satuan dan pemasok
inventorydita/fe_inventory pull request #2
Opened 2021-06-20 22:52 UTC by kevinriah

2021-06-21 07:33 UTC, kevinriah commented
Bismillah, semoga ga disemprot mas trian

2021-06-21 10:07 UTC, triandamai commented on src/views/barang/detailbarang.vue
> +      return this.shuffleArray(usersData.slice(0))
ini ganti aja jadi `return []` biar table nya kosong

2021-06-21 10:07 UTC, triandamai commented on src/views/data/header_pemasok.json
> +[
file ini hapus aja

2021-06-21 10:08 UTC, triandamai commented on src/views/data/header_pembelian.json
> +[
hapus juga file ini

2021-06-21 10:08 UTC, triandamai requested changes
ubah dulu ya

2021-06-22 13:33 UTC, triandamai approved these changes

2021-06-22 13:33 UTC, merged